### PR TITLE
Add Q.after

### PR DESCRIPTION
**Pull request by euwest**
I ran into a situation the other day where this would have been useful, so here's a PR for it. I think/hope the tests do a decent job of documenting my intentions, but here's a generalized use-case:
```js
var promiseA = someSource;
var promiseB = anotherSource;

promiseA
    .after(promiseB)
    .then(continueWithA, dealWithRejection);
```

On fulfillment of `promiseB`, `promiseA` will be allowed to proceed on to `.then`, being either fulfilled or rejected itself(and handled accordingly). However, if `promiseB` is rejected it causes `after` to abandon `promiseA`(regardless of its state) and send the rejected `promiseB` to `dealWithRejection`

All thoughts and suggestions are welcome. :koala:

### CODE REVIEW

**Comment by arikon** [comment]
It could be replaced with:

```js
var promiseA = someSource;
var promiseB = anotherSource;

promiseA
    .then(function(res) {
        return promiseB.thenResolve(res);
    })
    .then(continueWithA, dealWithRejection);
```

**Comment by euwest** [comment]
you're right @arikon, I guess the difference is `after` would allow you to track the progress of `promiseB` easily/cleanly:
```js
...
promiseA
    .after(promiseB, progressOfB)
    .then(continueWithA, dealWithRejection, progressOfA);
```

**Comment by euwest** [comment]
Also in your alternative if both promises are rejected `promiseA` will be passed to `dealWithRejection`. With `after`, `promiseB` takes precedence(which--I think--is conveyed semantically when reading the chain `promise.after(otherPromise).then(...)` ). To get this behavior within the confines of `then` and `thenResolve` you would need to have something like this:
```js
...
promiseA
    .then(function(res) {
        return promiseB.thenResolve(res);
    }, function(err) {
        return promiseB.thenReject(err);
    })
    .then(continueWithA, dealWithRejection);
```
...at which point I feel like it's worthwhile to encapsulate that behavior within a single function.

**Comment by kriskowal** [comment]
I am pushing way back on adding new features since feature creep has already gone too far. However, this is not a bad idea. Not because it is convenient, but because it conveys more information for the purpose of estimating time to completion. With the desugared version you illustrate, the resulting promise would not have a good way to infer time to fulfillment, but with `a.after(b)`, the ETF is clearly `max([a.etf, b.etf])`, just like `Q.all([a, b])`. As such, it might be good to implement `after` in terms of `all` in v2.

I’m on the fence, but these are my thoughts.

**Comment by euwest** [comment]
> As such, it might be good to implement after in terms of all in v2.

Sounds good. I'll give that a shot and make a pull against v2 for further mulling.

**Pull request closed without merging**
