### PR TITLE
Update q-spec.js

### PR DESCRIPTION
**Pull request by RohitPaul0007**

### CODE REVIEW

**Comment by benjamingr** [comment]
Hey, the library is mostly frozen except for critical bug fixes

**Review by kriskowal — COMMENTED** [review]
Thank you for your contribution. I appreciate the modernization, but since this is not broken, I’m inclined to leave it in its original form and capable of being run with the runtimes of its time.

**Comment by RohitPaul0007** [comment]
Thanks . I would like to know something. I am in my freshman year. It will be really great if there is any project you are working  and I can contribute and learn. (https://twitter.com/iinovativemind)

**Comment by benjamingr** [comment]
@RohitPaul0007 Node.js and Sinon both have stuff to do, e.g. https://github.com/sinonjs/fake-timers/issues/469

**Comment by kriskowal** [comment]
The next steps in the evolution of promises into handles for remote objects for the purposes of passing messages is happening here https://github.com/endojs/endo/tree/master/packages/eventual-send

Q does this (with Q-Connection). Native promises do not. The eventual shim builds promise message pipelining up on top of native promises to the degree that it’s possible to emulate what Q does (It’s not 100%, but it’s still good!), with the hopes that we’ll get the rest of the Q architecture into native promises one day.

Read the Q design through to the end to see what’s missing from native Promise https://github.com/kriskowal/q/tree/master/design

We’re doing a lot of work at @agoric in the @endojs project that you may find interesting if you’ve found your way to Q.

**Pull request closed without merging**
