### PR TITLE
add bower.json with proper exlcudes

### PR DESCRIPTION
**Pull request by joscha**
When managing q through bower, the package is quite big and contains a lot of resources that are not needed for web dev/production:

```console
.
├── CHANGES.md
├── CONTRIBUTING.md
├── Gruntfile.js
├── LICENSE
├── README.md
├── VERSIONS.md
├── benchmark
│   ├── compare-with-callbacks.js
│   └── scenarios.js
├── bower.json
├── design
│   ├── README.js
│   ├── q0.js
│   ├── q1.js
│   ├── q2.js
│   ├── q3.js
│   ├── q4.js
│   ├── q5.js
│   ├── q6.js
│   └── q7.js
├── examples
│   ├── all.js
│   └── async-generators
│       ├── 0.html
│       ├── 1-return.js
│       ├── 2-error-propagation.js
│       ├── 3-spawn.js
│       ├── 4-flow-control.js
│       └── README.md
├── package.json
├── q.js
├── q.png
├── q.svg
├── queue.js
├── ref_send.md
└── spec
    ├── aplus-adapter.js
    ├── lib
    │   ├── jasmine-1.2.0
    │   │   ├── MIT.LICENSE
    │   │   ├── jasmine-html.js
    │   │   ├── jasmine.css
    │   │   └── jasmine.js
    │   └── jasmine-promise.js
    ├── q-spec.html
    ├── q-spec.js
    └── queue-spec.js
```

This PR introduces a `bower.json` with according excludes.

### CODE REVIEW

**Comment by grahamscott** [comment]
+1 This is causing us issues in our build step, as we're running everything through uglify, which then pukes on the examples directory. We can work around it, but I dont think these superfluous files should be pulled down by bower.

**Comment by domenic** [comment]
Using bower to consume q is not a supported scenario. Please use npm.

**Comment by joscha** [comment]
@domenic if you merged that pull request it could be a supported scenario?!

**Comment by kriskowal** [comment]
We have no interest in maintaining duplicate information for multiple package managers. If you can get what you need by adding information to package.json instead of replicating package.json, we would be amenable.

**Comment by joscha** [comment]
unfortunately putting it in the package.json does not work - I guess everyone using it via bower has to exclude the resources in the build step manually then...

**Pull request closed without merging**
