### PR TITLE
Add Q.sequence

### PR DESCRIPTION
**Pull request by JixunMoe**
A simple sequence function.

## Syntax
```text
Q.sequence(arrData, fnCallback, ctx);
arrData: An array of data to be used.  
fnCallback: Returns a promise, accepts 1 argument (the array item).  
ctx: Context for fnCallback.
```

## Example
```js
var Q = require('q');

var data = ["first", "second", "third", "fourth"];
function main(){
    Q.sequence(data, proc_data).done(function (vals) {
        console.info(vals);
    });
}

function proc_data (t){
    console.info('> %s', t);
    var deferred = Q.defer();
    setTimeout(deferred.resolve, 50, "recv: "+ t);
    return deferred.promise;
}

main();
```

### CODE REVIEW

**Comment by sqren** [comment]
I support the idea of having a `Q.sequence` method but your implementation looks overly complicated. It can be solved with `Array.prototype.reduce`:
```
function sequence(array, iterator) {
    return array.reduce(function(promise, item) {
        return promise.then(function () {
            return iterator(item);
        });
    }, Q());
};
```

**Comment by JixunMoe** [comment]
I'm not familiar with `reduce`, so I did it alternatively.

Your code indeed looks better than mine, can you post a standalone PR? Then I'll close this one,  thanks.

**Comment by kriskowal** [comment]
I advocate direct use of the reduce/Q.when/Q idiom. It’s in the README https://github.com/kriskowal/q#sequences

**Comment by JixunMoe** [comment]
Thanks :D

**Pull request closed without merging**
