### PR TITLE
ref #621 Q.consume

### PR DESCRIPTION
**Pull request by piglovesyou**
I implemented "Q.consume" function for an issue #621.

Any advice of naming variables and style of coding would be appreciated.

### CODE REVIEW

**Comment by jtmarmon** [comment]
@piglovesyou thanks so much for this pr. ran into this weird edge case today when dealing with a worker task processing an array of ~28k elements. 

how many concurrent items should I be processing? 5? 10? 100?

**Comment by piglovesyou** [comment]
@jtmarmon It is hard to find out the most efficient number because there must be many factors to be a problem: out of memory, hunging up of an opposit server response, so on. How about `5` as a start? In this case it's better to take stability instead of speed.

**Comment by jtmarmon** [comment]
hmm, it's odd, I tried reducing the number a fair amount and couldn't quite get anything to work. I ended up resorting to async as a temporary replacement

**Comment by piglovesyou** [comment]
If you don't care to provide the error log and the execution code I would like to see them.

**Comment by jtmarmon** [comment]
no error log, the `.then` simply never gets called.

essentially the program looks like

```
doThing()
.then(function() {
  return Q.all(R.map(execute, data));
})
```

Works perfectly fine with 50 data points. Not so with 28,000.  I tried it with your code, replacing line 3 with `return Q.consume(execute, data, 50)` to no avail. Again, the .then wrapping this method was never executed

**Comment by piglovesyou** [comment]
`.catch(function(err) { console.log(err.stack) })` might show an error log. I'm not familiar to `R`...

**Comment by piglovesyou** [comment]
In https://github.com/kriskowal/q/issues/621#issuecomment-92546791, @kriskowal suggested me that the problem should be dealt in q-io. The PR is too small-scoped in the case so I'll close.

**Pull request closed without merging**
